doc: add `@swc/core` dependency to usage example
On a fresh repo, running the previous example would result in a `Error: Cannot find module '@swc/core'` otherwise.

I think it'd also be good to add `@swc/core` as a peer dependency to `@swc-node/register`, so that `@swc/core` will be installed automatically when missing.